export const playDataInit = {
  first: 0,
  turn: 1,
  round: 0,
  phase: 0,
  players: [
    {
      name: "1",
      resource: {
        wood: 0,
        clay: 0,
        reed: 0,
        stone: 0,
        grain: 0,
        vegetable: 0,
        sheep: 0,
        boar: 0,
        cattle: 0,
        food: 0,
        family: 2,
        room: 2,
        fence: 0,
        barn: 0,
      },
      fields: [
        {
          field_type: "room",
          position: 6,
          is_in: {
            family: 1,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "room",
          position: 11,
          is_in: {
            family: 1,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
      ],
      house_type: "wood",
      fences: {},
      cards: [
        {
          card_number: "JOB_04",
          name: "\ub9c8\ubd80",
          score: 0,
          is_use: false,
        },
        {
          card_number: "JOB_11",
          name: "\uc9c0\ubd95 \ub2e4\uc9c0\ub294 \uc0ac\ub78c",
          score: 0,
          is_use: false,
        },
        {
          card_number: "JOB_15",
          name: "\uc591\ubd80\ubaa8",
          score: 0,
          is_use: false,
        },
        {
          card_number: "JOB_39",
          name: "\uc591 \ubcf4\ud589\uc790",
          score: 0,
          is_use: false,
        },
        {
          card_number: "JOB_23",
          name: "\uc624\ub450\ub9c9\uc9d1\uc0b4\uc774",
          score: 0,
          is_use: false,
        },
        {
          card_number: "JOB_30",
          name: "\uc9c0\uc9c8\ud559\uc790",
          score: 0,
          is_use: false,
        },
        {
          card_number: "JOB_35",
          name: "\ubc84\uc12f \ub530\ub294 \uc0ac\ub78c",
          score: 0,
          is_use: false,
        },
        {
          card_number: "SUB_FAC_03",
          name: "\uc5f0\ubabb \uc624\ub450\ub9c9",
          score: 1,
          is_use: false,
        },
        {
          card_number: "SUB_FAC_39",
          name: "\ubb3c\ud1b5",
          score: 0,
          is_use: false,
        },
        {
          card_number: "SUB_FAC_22",
          name: "\ud3d0\ud488 \ucc3d\uace0",
          score: 0,
          is_use: false,
        },
        {
          card_number: "SUB_FAC_31",
          name: "\ub178\uc810",
          score: 0,
          is_use: false,
        },
        {
          card_number: "SUB_FAC_33",
          name: "\uc6b0\uc2dc\uc7a5",
          score: 0,
          is_use: false,
        },
        {
          card_number: "SUB_FAC_28",
          name: "\uacbd\uc9c8 \uc790\uae30",
          score: 0,
          is_use: false,
        },
        {
          card_number: "SUB_FAC_26",
          name: "\uc774\uc911\ub0a0 \uc7c1\uae30",
          score: 0,
          is_use: false,
        },
      ],
    },
    {
      name: "2",
      resource: {
        wood: 0,
        clay: 0,
        reed: 0,
        stone: 0,
        grain: 0,
        vegetable: 0,
        sheep: 0,
        boar: 0,
        cattle: 0,
        food: 0,
        family: 2,
        room: 2,
        fence: 0,
        barn: 0,
      },
      fields: [
        {
          field_type: "room",
          position: 6,
          is_in: {
            family: 1,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "room",
          position: 11,
          is_in: {
            family: 1,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
      ],
      house_type: "wood",
      fences: {},
      cards: [
        {
          card_number: "JOB_03",
          name: "\ubcbd \uac74\ucd95\uac00",
          score: 0,
          is_use: false,
        },
        {
          card_number: "JOB_05",
          name: "\uc18c\uaddc\ubaa8 \ub18d\ubd80",
          score: 0,
          is_use: false,
        },
        {
          card_number: "JOB_21",
          name: "\uc7a5\uc791 \ucc44\uc9d1\uc790",
          score: 0,
          is_use: false,
        },
        {
          card_number: "JOB_37",
          name: "\ub9c8\uc220\uc0ac",
          score: 0,
          is_use: false,
        },
        {
          card_number: "JOB_31",
          name: "\ub098\ubb47\uac00\uc9c0 \ubaa8\uc73c\ub294 \uc0ac\ub78c",
          score: 0,
          is_use: false,
        },
        {
          card_number: "JOB_07",
          name: "\ud559\uc790",
          score: 0,
          is_use: false,
        },
        {
          card_number: "JOB_18",
          name: "\ucc44\uc18c \uc7a5\uc218",
          score: 0,
          is_use: false,
        },
        {
          card_number: "SUB_FAC_06",
          name: "\uc190\uc7c1\uae30",
          score: 0,
          is_use: false,
        },
        {
          card_number: "SUB_FAC_20",
          name: "\uac1c\uc6b8",
          score: 0,
          is_use: false,
        },
        {
          card_number: "SUB_FAC_14",
          name: "\ud1b5\ub098\ubb34\ubc30",
          score: 1,
          is_use: false,
        },
        {
          card_number: "SUB_FAC_12",
          name: "\ud0c0\uc791\ud310",
          score: 1,
          is_use: false,
        },
        { card_number: "SUB_FAC_35", name: "\ubcd1", score: 4, is_use: false },
        {
          card_number: "SUB_FAC_08",
          name: "\ub3c4\ud1a0\ub9ac \ubc14\uad6c\ub2c8",
          score: 0,
          is_use: false,
        },
        {
          card_number: "SUB_FAC_24",
          name: "\ub124\ub35c\ub780\ub4dc\uc2dd \ud48d\ucc28",
          score: 2,
          is_use: false,
        },
      ],
    },
    {
      name: "3",
      resource: {
        wood: 0,
        clay: 0,
        reed: 0,
        stone: 0,
        grain: 0,
        vegetable: 0,
        sheep: 0,
        boar: 0,
        cattle: 0,
        food: 0,
        family: 2,
        room: 2,
        fence: 0,
        barn: 0,
      },
      fields: [
        {
          field_type: "room",
          position: 6,
          is_in: {
            family: 1,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "room",
          position: 11,
          is_in: {
            family: 1,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
      ],
      house_type: "wood",
      fences: {},
      cards: [
        {
          card_number: "JOB_34",
          name: "\ub098\ubb34\uafbc",
          score: 0,
          is_use: false,
        },
        {
          card_number: "JOB_29",
          name: "\uac00\ucd95 \uc0c1\uc778",
          score: 0,
          is_use: false,
        },
        {
          card_number: "JOB_25",
          name: "\ucc3d\uace0 \uad00\ub9ac\uc778",
          score: 0,
          is_use: false,
        },
        {
          card_number: "JOB_08",
          name: "\ud558\uc778",
          score: 0,
          is_use: false,
        },
        {
          card_number: "JOB_27",
          name: "\uc219\ub828 \ubcbd\ub3cc\uacf5",
          score: 0,
          is_use: false,
        },
        {
          card_number: "JOB_13",
          name: "\uc0ac\uc81c",
          score: 0,
          is_use: false,
        },
        {
          card_number: "JOB_33",
          name: "\ubcf4\uc870 \uacbd\uc791\uc790",
          score: 0,
          is_use: false,
        },
        {
          card_number: "SUB_FAC_13",
          name: "\ub2e4\uc9c4 \ud759",
          score: 0,
          is_use: false,
        },
        {
          card_number: "SUB_FAC_07",
          name: "\uc6b8\ucc3d\ud55c \uc232",
          score: 0,
          is_use: false,
        },
        {
          card_number: "SUB_FAC_18",
          name: "\uc591\ud1a0 \ucc44\uad74\uc7a5",
          score: 1,
          is_use: false,
        },
        {
          card_number: "SUB_FAC_23",
          name: "\ube75\uc0bd",
          score: 0,
          is_use: false,
        },
        {
          card_number: "SUB_FAC_30",
          name: "\ud759\ud310",
          score: 0,
          is_use: false,
        },
        {
          card_number: "SUB_FAC_02",
          name: "\ub300\ud615\uc628\uc2e4",
          score: 0,
          is_use: false,
        },
        {
          card_number: "SUB_FAC_09",
          name: "\uc6b0\uc720 \uc8fc\uc804\uc790",
          score: 0,
          is_use: false,
        },
      ],
    },
    {
      name: "4",
      resource: {
        wood: 0,
        clay: 0,
        reed: 0,
        stone: 0,
        grain: 0,
        vegetable: 0,
        sheep: 0,
        boar: 0,
        cattle: 0,
        food: 0,
        family: 2,
        room: 2,
        fence: 0,
        barn: 0,
      },
      fields: [
        {
          field_type: "room",
          position: 6,
          is_in: {
            family: 1,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "room",
          position: 11,
          is_in: {
            family: 1,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
      ],
      house_type: "wood",
      fences: {},
      cards: [
        {
          card_number: "JOB_20",
          name: "\uc18c \uc0ac\uc721\uc0ac",
          score: 0,
          is_use: false,
        },
        {
          card_number: "JOB_12",
          name: "\uc0c1\ub2f4\uac00",
          score: 0,
          is_use: false,
        },
        {
          card_number: "JOB_24",
          name: "\uc791\uc0b4\uafbc",
          score: 0,
          is_use: false,
        },
        {
          card_number: "JOB_16",
          name: "\uc7ac\uc0b0\uad00\ub9ac\uc778",
          score: 0,
          is_use: false,
        },
        {
          card_number: "JOB_32",
          name: "\ubaa9\uc218",
          score: 0,
          is_use: false,
        },
        {
          card_number: "JOB_36",
          name: "\ucd08\ubcbd\uc9c8\uacf5",
          score: 0,
          is_use: false,
        },
        {
          card_number: "JOB_14",
          name: "\uac00\ub9c8 \ub5bc\ub294 \uc0ac\ub78c",
          score: 0,
          is_use: false,
        },
        {
          card_number: "SUB_FAC_19",
          name: "\ubaa9\uc7ac\uc18c",
          score: 2,
          is_use: false,
        },
        {
          card_number: "SUB_FAC_10",
          name: "\uccad\uc5b4 \ub0c4\ube44",
          score: 0,
          is_use: false,
        },
        {
          card_number: "SUB_FAC_15",
          name: "\ucc44\uad74 \ub9dd\uce58",
          score: 0,
          is_use: false,
        },
        {
          card_number: "SUB_FAC_38",
          name: "\uc0bc\ud3ec\uc2dd \ub18d\ubc95",
          score: 0,
          is_use: false,
        },
        {
          card_number: "SUB_FAC_05",
          name: "\ub538\uae30\ud3ec",
          score: 2,
          is_use: false,
        },
        {
          card_number: "SUB_FAC_16",
          name: "\ubc14\uad6c\ub2c8",
          score: 0,
          is_use: false,
        },
        {
          card_number: "SUB_FAC_21",
          name: "\uace1\uc2dd\uc6a9 \uc0bd",
          score: 0,
          is_use: false,
        },
      ],
    },
  ],
  actions: [],
  base_cards: [
    {
      card_number: "BASE_01",
      is_stacked: true,
      count: 1,
      resource: { wood: 0 },
      additional_action: null,
      player: 0,
    },
    {
      card_number: "BASE_02",
      is_stacked: true,
      count: 2,
      resource: { wood: 2 },
      additional_action: null,
      player: null,
    },
    {
      card_number: "BASE_03",
      is_stacked: false,
      count: 0,
      resource: { reed: 1, food: 1, stone: 1 },
      additional_action: null,
      player: null,
    },
    {
      card_number: "BASE_04",
      is_stacked: true,
      count: 2,
      resource: { clay: 2 },
      additional_action: null,
      player: null,
    },
    {
      card_number: "BASE_05",
      is_stacked: false,
      count: 0,
      resource: null,
      additional_action: null,
      player: null,
    },
    {
      card_number: "BASE_06",
      is_stacked: true,
      count: 1,
      resource: { food: 1 },
      additional_action: null,
      player: null,
    },
    {
      card_number: "BASE_07",
      is_stacked: false,
      count: 0,
      resource: null,
      additional_action: null,
      player: null,
    },
    {
      card_number: "BASE_08",
      is_stacked: false,
      count: 0,
      resource: null,
      additional_action: null,
      player: null,
    },
    {
      card_number: "BASE_09",
      is_stacked: false,
      count: 0,
      resource: { grain: 1 },
      additional_action: null,
      player: null,
    },
    {
      card_number: "BASE_10",
      is_stacked: false,
      count: 0,
      resource: null,
      additional_action: null,
      player: null,
    },
    {
      card_number: "BASE_11",
      is_stacked: false,
      count: 0,
      resource: null,
      additional_action: null,
      player: null,
    },
    {
      card_number: "BASE_12",
      is_stacked: false,
      count: 0,
      resource: { food: 2 },
      additional_action: null,
      player: null,
    },
    {
      card_number: "BASE_13",
      is_stacked: true,
      count: 3,
      resource: { wood: 3 },
      additional_action: null,
      player: null,
    },
    {
      card_number: "BASE_14",
      is_stacked: true,
      count: 1,
      resource: { clay: 1 },
      additional_action: null,
      player: null,
    },
    {
      card_number: "BASE_15",
      is_stacked: true,
      count: 1,
      resource: { reed: 1 },
      additional_action: null,
      player: null,
    },
    {
      card_number: "BASE_16",
      is_stacked: true,
      count: 1,
      resource: { food: 1 },
      additional_action: null,
      player: null,
    },
  ],
  round_cards: [
    {
      card_number: "ACTION_09",
      is_stacked: false,
      count: 0,
      resource: { vegetable: 1 },
      additional_action: null,
      player: null,
    },
    {
      card_number: "ACTION_01",
      is_stacked: false,
      count: 0,
      resource: null,
      additional_action: null,
      player: null,
    },
    {
      card_number: "ACTION_02",
      is_stacked: false,
      count: 0,
      resource: null,
      additional_action: null,
      player: null,
    },
    {
      card_number: "ACTION_04",
      is_stacked: true,
      count: 1,
      resource: { sheep: 0 },
      additional_action: null,
      player: null,
    },
    {
      card_number: "ACTION_03",
      is_stacked: false,
      count: 0,
      resource: null,
      additional_action: null,
      player: null,
    },
    {
      card_number: "ACTION_07",
      is_stacked: false,
      count: 0,
      resource: null,
      additional_action: null,
      player: null,
    },
    {
      card_number: "ACTION_06",
      is_stacked: false,
      count: 0,
      resource: null,
      additional_action: null,
      player: null,
    },
    {
      card_number: "ACTION_05",
      is_stacked: true,
      count: 1,
      resource: { stone: 0 },
      additional_action: null,
      player: null,
    },

    {
      card_number: "ACTION_08",
      is_stacked: true,
      count: 1,
      resource: { boar: 0 },
      additional_action: null,
      player: null,
    },
    {
      card_number: "ACTION_11",
      is_stacked: true,
      count: 1,
      resource: { cattle: 0 },
      additional_action: null,
      player: null,
    },
    {
      card_number: "ACTION_10",
      is_stacked: true,
      count: 1,
      resource: { stone: 0 },
      additional_action: null,
      player: null,
    },
    {
      card_number: "ACTION_13",
      is_stacked: false,
      count: 0,
      resource: null,
      additional_action: null,
      player: null,
    },
    {
      card_number: "ACTION_12",
      is_stacked: false,
      count: 0,
      resource: null,
      additional_action: null,
      player: null,
    },
    {
      card_number: "ACTION_14",
      is_stacked: false,
      count: 0,
      resource: null,
      additional_action: null,
      player: null,
    },
  ],
  common_resources: {
    wood: 24,
    clay: 21,
    reed: 13,
    stone: 16,
    grain: 24,
    vegetable: 16,
    sheep: 18,
    boar: 15,
    cattle: 13,
    food: 74,
    family: 0,
    room: 0,
    fence: 0,
    barn: 0,
  },
};

export const createRoom = {
  room_id: 0,
  host: "User",
  option: {
    title: " ",
    is_chat: null,
    mode: null,
    time: null,
    password: null,
  },
  participant: [],
};

export const RoomData1 = {
  room_id: 1,
  host: "Player 1",
  option: {
    title: "Room 1",
    is_chat: false,
    mode: "public",
    time: 30,
    password: "1234",
  },
  participant: [
    {
      name: "Player 1",
      img: "https://i.imgur.com/1Q2QXem.png",
      user_detail: "rest_endPoint2",
    },
    {
      name: "Player 2",
      img: "https://i.imgur.com/1Q2QXem.png",
      user_detail: "rest_endPoint2",
    },
    {
      name: "Player 3",
      img: "https://i.imgur.com/1Q2QXem.png",
      user_detail: "rest_endPoint3",
    },
    {
      name: "Player 4",
      img: "https://i.imgur.com/1Q2QXem.png",
      user_detail: "rest_endPoint4",
    },
  ],
};

export const RoomData2 = {
  room_id: 2,
  host: "윤호",
  option: {
    title: "일해라 노예야",
    is_chat: true,
    mode: "private",
    time: 30,
    password: "1234",
  },
  participant: [
    {
      name: "재훈",
      img: "https://i.imgur.com/1Q2QXem.png",
      user_detail: "rest_endPoint2",
    },
    {
      name: "준수",
      img: "https://i.imgur.com/1Q2QXem.png",
      user_detail: "rest_endPoint2",
    },
    {
      name: "윤호",
      img: "https://i.imgur.com/1Q2QXem.png",
      user_detail: "rest_endPoint3",
    },
  ],
};

// TODO : socket 통신 시에는 각 방의 정보만 받아옴
export const detailRoomData = {
  data: [createRoom, RoomData1, RoomData2],
};

export const lobbyData = {
  room_list: [
    {
      room_id: 1,
      host: "Player 1",
      option: {
        title: "Room 1",
        is_chat: true,
        mode: "public",
        time: 30,
        password: null,
      },
      participant: [
        {
          name: "Player 1",
          img: "https://i.imgur.com/1Q2QXem.png",
          user_detail: "rest_endPoint2",
        },
        {
          name: "Player 2",
          img: "https://i.imgur.com/1Q2QXem.png",
          user_detail: "rest_endPoint2",
        },
        {
          name: "Player 3",
          img: "https://i.imgur.com/1Q2QXem.png",
          user_detail: "rest_endPoint3",
        },
        {
          name: "Player 4",
          img: "https://i.imgur.com/1Q2QXem.png",
          user_detail: "rest_endPoint4",
        },
      ],
    },
    {
      room_id: 2,
      host: "재훈",
      option: {
        title: "일해라 노예야",
        is_chat: true,
        mode: "private",
        time: 30,
        password: "1234",
      },
      participant: [
        {
          name: "재훈",
          img: "https://i.imgur.com/1Q2QXem.png",
          user_detail: "rest_endPoint2",
        },
        {
          name: "Player 2",
          img: "https://i.imgur.com/1Q2QXem.png",
          user_detail: "rest_endPoint2",
        },
        {
          name: "Player 3",
          img: "https://i.imgur.com/1Q2QXem.png",
          user_detail: "rest_endPoint3",
        },
      ],
    },
  ],
};
