export const playDataInit = {
  first: 0,
  turn: 0,
  round: 0,
  phase: 0,
  players: [
    {
      name: "1",
      resource: {
        wood: 0,
        clay: 0,
        reed: 0,
        stone: 0,
        grain: 0,
        vegetable: 0,
        sheep: 0,
        boar: 0,
        cattle: 0,
        food: 3,
        family: 2,
        room: 2,
        fence: 0,
        barn: 0,
      },
      fields: [
        {
          field_type: "empty",
          position: 1,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 2,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 3,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 4,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 5,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 6,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 7,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 8,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 9,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 10,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 11,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 12,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 13,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "room",
          position: 14,
          is_in: {
            family: 1,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "room",
          position: 15,
          is_in: {
            family: 1,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
      ],
      house_type: "wood",
      fences: {},
      cards: [
        {
          card_number: "JOB_25",
          name: "창고 관리인",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_28",
          name: "돌 자르는 사람",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_35",
          name: "버섯 따는 사람",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_24",
          name: "작살꾼",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_02",
          name: "목사",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_12",
          name: "상담가",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_36",
          name: "초벽질공",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_11",
          name: "올가미 밧줄",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_02",
          name: "대형온실",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_33",
          name: "우시장",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_30",
          name: "흙판",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_18",
          name: "양토 채굴장",
          score: 1,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_21",
          name: "곡식용 삽",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_31",
          name: "노점",
          score: 0,
          is_used: false,
          used_round: null,
        },
      ],
    },
    {
      name: "2",
      resource: {
        wood: 0,
        clay: 0,
        reed: 0,
        stone: 0,
        grain: 0,
        vegetable: 0,
        sheep: 0,
        boar: 0,
        cattle: 0,
        food: 3,
        family: 2,
        room: 2,
        fence: 0,
        barn: 0,
      },
      fields: [
        {
          field_type: "empty",
          position: 1,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 2,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 3,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 4,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 5,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 6,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 7,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 8,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 9,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 10,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 11,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 12,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 13,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "room",
          position: 14,
          is_in: {
            family: 1,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "room",
          position: 15,
          is_in: {
            family: 1,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
      ],
      house_type: "wood",
      fences: {},
      cards: [
        {
          card_number: "JOB_26",
          name: "산울타리지기",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_06",
          name: "쟁기 몰이꾼",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_16",
          name: "재산관리인",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_34",
          name: "나무꾼",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_04",
          name: "마부",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_23",
          name: "오두막집살이",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_33",
          name: "보조 경작자",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_20",
          name: "개울",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_35",
          name: "병",
          score: 4,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_32",
          name: "작은 우리",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_14",
          name: "통나무배",
          score: 1,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_24",
          name: "네덜란드식 풍차",
          score: 2,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_10",
          name: "청어 냄비",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_03",
          name: "연못 오두막",
          score: 1,
          is_used: false,
          used_round: null,
        },
      ],
    },
    {
      name: "3",
      resource: {
        wood: 0,
        clay: 0,
        reed: 0,
        stone: 0,
        grain: 0,
        vegetable: 0,
        sheep: 0,
        boar: 0,
        cattle: 0,
        food: 3,
        family: 2,
        room: 2,
        fence: 0,
        barn: 0,
      },
      fields: [
        {
          field_type: "empty",
          position: 1,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 2,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 3,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 4,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 5,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 6,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 7,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 8,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 9,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 10,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 11,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 12,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 13,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "room",
          position: 14,
          is_in: {
            family: 1,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "room",
          position: 15,
          is_in: {
            family: 1,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
      ],
      house_type: "wood",
      fences: {},
      cards: [
        {
          card_number: "JOB_18",
          name: "채소 장수",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_32",
          name: "목수",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_19",
          name: "류트 연주자",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_31",
          name: "나뭇가지 모으는 사람",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_09",
          name: "무자식",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_22",
          name: "농번기 일꾼",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_03",
          name: "벽 건축가",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_12",
          name: "타작판",
          score: 1,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_07",
          name: "울창한 숲",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_13",
          name: "다진 흙",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_08",
          name: "도토리 바구니",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_37",
          name: "버터 제조기",
          score: 1,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_01",
          name: "부엌방",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_28",
          name: "경질 자기",
          score: 0,
          is_used: false,
          used_round: null,
        },
      ],
    },
    {
      name: "4",
      resource: {
        wood: 0,
        clay: 0,
        reed: 0,
        stone: 0,
        grain: 0,
        vegetable: 0,
        sheep: 0,
        boar: 0,
        cattle: 0,
        food: 3,
        family: 2,
        room: 2,
        fence: 0,
        barn: 0,
      },
      fields: [
        {
          field_type: "empty",
          position: 1,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 2,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 3,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 4,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 5,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 6,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 7,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 8,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 9,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 10,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 11,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 12,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "empty",
          position: 13,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "room",
          position: 14,
          is_in: {
            family: 1,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
        {
          field_type: "room",
          position: 15,
          is_in: {
            family: 1,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
        },
      ],
      house_type: "wood",
      fences: {},
      cards: [
        {
          card_number: "JOB_05",
          name: "소규모 농부",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_39",
          name: "양 보행자",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_30",
          name: "지질학자",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_07",
          name: "학자",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_21",
          name: "장작 채집자",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_37",
          name: "마술사",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_15",
          name: "양부모",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_38",
          name: "삼포식 농법",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_34",
          name: "이동 경작",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_17",
          name: "목수의 객실",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_23",
          name: "빵삽",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_19",
          name: "목재소",
          score: 2,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_15",
          name: "채굴 망치",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_25",
          name: "돌 집게",
          score: 0,
          is_used: false,
          used_round: null,
        },
      ],
    },
  ],
  actions: [],
  base_cards: [
    {
      card_number: "BASE_01",
      is_stacked: true,
      count: 1,
      resource: {
        wood: 1,
      },
      additional_action: {
        0: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        1: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        2: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        3: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "BASE_02",
      is_stacked: true,
      count: 2,
      resource: {
        wood: 2,
      },
      additional_action: {
        0: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        1: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        2: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        3: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "BASE_03",
      is_stacked: false,
      count: 0,
      resource: {
        reed: 1,
        food: 1,
        stone: 1,
      },
      additional_action: {
        0: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        1: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        2: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        3: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "BASE_04",
      is_stacked: true,
      count: 2,
      resource: {
        clay: 2,
      },
      additional_action: {
        0: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        1: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        2: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        3: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "BASE_05",
      is_stacked: false,
      count: 0,
      resource: null,
      additional_action: {
        0: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        1: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        2: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        3: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "BASE_06",
      is_stacked: true,
      count: 1,
      resource: {
        food: 1,
      },
      additional_action: {
        0: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        1: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        2: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        3: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "BASE_07",
      is_stacked: false,
      count: 0,
      resource: null,
      additional_action: {
        0: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        1: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        2: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        3: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "BASE_08",
      is_stacked: false,
      count: 0,
      resource: null,
      additional_action: {
        0: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        1: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        2: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        3: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "BASE_09",
      is_stacked: false,
      count: 0,
      resource: {
        grain: 1,
      },
      additional_action: {
        0: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        1: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        2: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        3: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "BASE_10",
      is_stacked: false,
      count: 0,
      resource: null,
      additional_action: {
        0: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        1: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        2: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        3: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "BASE_11",
      is_stacked: false,
      count: 0,
      resource: null,
      additional_action: {
        0: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        1: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        2: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        3: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "BASE_12",
      is_stacked: false,
      count: 0,
      resource: {
        food: 2,
      },
      additional_action: {
        0: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        1: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        2: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        3: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "BASE_13",
      is_stacked: true,
      count: 3,
      resource: {
        wood: 3,
      },
      additional_action: {
        0: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        1: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        2: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        3: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "BASE_14",
      is_stacked: true,
      count: 1,
      resource: {
        clay: 1,
      },
      additional_action: {
        0: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        1: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        2: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        3: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "BASE_15",
      is_stacked: true,
      count: 1,
      resource: {
        reed: 1,
      },
      additional_action: {
        0: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        1: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        2: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        3: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "BASE_16",
      is_stacked: true,
      count: 1,
      resource: {
        food: 1,
      },
      additional_action: {
        0: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        1: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        2: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        3: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
  ],
  round_cards: [
    {
      card_number: "ACTION_04",
      is_stacked: true,
      count: 1,
      resource: {
        sheep: 1,
      },
      additional_action: {
        0: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        1: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        2: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        3: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "ACTION_02",
      is_stacked: false,
      count: 0,
      resource: null,
      additional_action: {
        0: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        1: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        2: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        3: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "ACTION_01",
      is_stacked: false,
      count: 0,
      resource: null,
      additional_action: {
        0: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        1: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        2: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        3: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "ACTION_03",
      is_stacked: false,
      count: 0,
      resource: null,
      additional_action: {
        0: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        1: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        2: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        3: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "ACTION_05",
      is_stacked: true,
      count: 1,
      resource: {
        stone: 0,
      },
      additional_action: {
        0: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        1: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        2: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        3: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "ACTION_07",
      is_stacked: false,
      count: 0,
      resource: null,
      additional_action: {
        0: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        1: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        2: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        3: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "ACTION_06",
      is_stacked: false,
      count: 0,
      resource: null,
      additional_action: {
        0: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        1: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        2: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        3: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "ACTION_08",
      is_stacked: true,
      count: 1,
      resource: {
        boar: 0,
      },
      additional_action: {
        0: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        1: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        2: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        3: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "ACTION_09",
      is_stacked: false,
      count: 0,
      resource: {
        vegetable: 1,
      },
      additional_action: {
        0: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        1: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        2: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        3: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "ACTION_10",
      is_stacked: true,
      count: 1,
      resource: {
        stone: 0,
      },
      additional_action: {
        0: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        1: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        2: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        3: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "ACTION_11",
      is_stacked: true,
      count: 1,
      resource: {
        cattle: 0,
      },
      additional_action: {
        0: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        1: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        2: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        3: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "ACTION_12",
      is_stacked: false,
      count: 0,
      resource: null,
      additional_action: {
        0: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        1: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        2: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        3: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "ACTION_13",
      is_stacked: false,
      count: 0,
      resource: null,
      additional_action: {
        0: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        1: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        2: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        3: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "ACTION_14",
      is_stacked: false,
      count: 0,
      resource: null,
      additional_action: {
        0: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        1: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        2: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        3: {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
  ],
  primary_cards: [
    {
      card_number: "PRI_FAC_01",
      owner: null,
    },
    {
      card_number: "PRI_FAC_02",
      owner: null,
    },
    {
      card_number: "PRI_FAC_03",
      owner: null,
    },
    {
      card_number: "PRI_FAC_04",
      owner: null,
    },
    {
      card_number: "PRI_FAC_05",
      owner: null,
    },
    {
      card_number: "PRI_FAC_06",
      owner: null,
    },
    {
      card_number: "PRI_FAC_07",
      owner: null,
    },
    {
      card_number: "PRI_FAC_08",
      owner: null,
    },
  ],
  common_resources: {
    wood: 24,
    clay: 21,
    reed: 13,
    stone: 16,
    grain: 24,
    vegetable: 16,
    sheep: 17,
    boar: 15,
    cattle: 13,
    food: 74,
    family: 0,
    room: 0,
    fence: 0,
    barn: 0,
  },
};
export const createRoom = {
  room_id: 0,
  host: "User",
  option: {
    title: " ",
    is_chat: null,
    mode: null,
    time: null,
    password: null,
  },
  participant: [],
};

export const RoomData1 = {
  room_id: 1,
  host: "Player 1",
  option: {
    title: "Room 1",
    is_chat: false,
    mode: "public",
    time: 30,
    password: "1234",
  },
  participant: [
    {
      name: "Player 1",
      img: "https://i.imgur.com/1Q2QXem.png",
      user_detail: "rest_endPoint2",
    },
    {
      name: "Player 2",
      img: "https://i.imgur.com/1Q2QXem.png",
      user_detail: "rest_endPoint2",
    },
    {
      name: "Player 3",
      img: "https://i.imgur.com/1Q2QXem.png",
      user_detail: "rest_endPoint3",
    },
    {
      name: "Player 4",
      img: "https://i.imgur.com/1Q2QXem.png",
      user_detail: "rest_endPoint4",
    },
  ],
};

export const RoomData2 = {
  room_id: 2,
  host: "윤호",
  option: {
    title: "일해라 노예야",
    is_chat: true,
    mode: "private",
    time: 30,
    password: "1234",
  },
  participant: [
    {
      name: "재훈",
      img: "https://i.imgur.com/1Q2QXem.png",
      user_detail: "rest_endPoint2",
    },
    {
      name: "준수",
      img: "https://i.imgur.com/1Q2QXem.png",
      user_detail: "rest_endPoint2",
    },
    {
      name: "윤호",
      img: "https://i.imgur.com/1Q2QXem.png",
      user_detail: "rest_endPoint3",
    },
  ],
};

// TODO : socket 통신 시에는 각 방의 정보만 받아옴
export const detailRoomData = {
  data: [createRoom, RoomData1, RoomData2],
};

export const lobbyData = {
  room_list: [
    {
      room_id: 1,
      host: "Player 1",
      option: {
        title: "Room 1",
        is_chat: true,
        mode: "public",
        time: 30,
        password: null,
      },
      participant: [
        {
          name: "Player 1",
          img: "https://i.imgur.com/1Q2QXem.png",
          user_detail: "rest_endPoint2",
        },
        {
          name: "Player 2",
          img: "https://i.imgur.com/1Q2QXem.png",
          user_detail: "rest_endPoint2",
        },
        {
          name: "Player 3",
          img: "https://i.imgur.com/1Q2QXem.png",
          user_detail: "rest_endPoint3",
        },
        {
          name: "Player 4",
          img: "https://i.imgur.com/1Q2QXem.png",
          user_detail: "rest_endPoint4",
        },
      ],
    },
    {
      room_id: 2,
      host: "재훈",
      option: {
        title: "일해라 노예야",
        is_chat: true,
        mode: "private",
        time: 30,
        password: "1234",
      },
      participant: [
        {
          name: "재훈",
          img: "https://i.imgur.com/1Q2QXem.png",
          user_detail: "rest_endPoint2",
        },
        {
          name: "Player 2",
          img: "https://i.imgur.com/1Q2QXem.png",
          user_detail: "rest_endPoint2",
        },
        {
          name: "Player 3",
          img: "https://i.imgur.com/1Q2QXem.png",
          user_detail: "rest_endPoint3",
        },
      ],
    },
  ],
};
