export const playDataInit = {
  first: 0,
  turn: 0,
  round: 0,
  phase: 0,
  players: [
    {
      name: "1",
      resource: {
        wood: 30,
        clay: 24,
        reed: 14,
        stone: 16,
        grain: 24,
        vegetable: 16,
        sheep: 18,
        boar: 15,
        cattle: 13,
        food: 76,
        family: 2,
        room: 2,
        fence: 0,
        barn: 0,
      },
      fields: [
        {
          field_type: "cage",
          position: 1,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 2,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 3,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 4,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 5,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 6,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 7,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 8,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 9,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 10,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 11,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 12,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 13,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "room",
          position: 14,
          is_in: {
            family: 1,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "room",
          position: 15,
          is_in: {
            family: 1,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
      ],
      house_type: "wood",
      fences: null,
      cards: [
        {
          card_number: "JOB_03",
          name: "\ubcbd \uac74\ucd95\uac00",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_03",
          name: "\ubcbd \uac74\ucd95\uac00",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_03",
          name: "\ubcbd \uac74\ucd95\uac00",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_03",
          name: "\ubcbd \uac74\ucd95\uac00",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_03",
          name: "\ubcbd \uac74\ucd95\uac00",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_03",
          name: "\ubcbd \uac74\ucd95\uac00",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_03",
          name: "\ubcbd \uac74\ucd95\uac00",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_38",
          name: "\uc0bc\ud3ec\uc2dd \ub18d\ubc95",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_11",
          name: "\uc62c\uac00\ubbf8 \ubc27\uc904",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_27",
          name: "\uc1e0\uc2a4\ub791",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_36",
          name: "\uac70\ub300 \ub18d\uc7a5",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_39",
          name: "\ubb3c\ud1b5",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_28",
          name: "\uacbd\uc9c8 \uc790\uae30",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_07",
          name: "\uc6b8\ucc3d\ud55c \uc232",
          score: 0,
          is_used: false,
          used_round: null,
        },
      ],
    },
    {
      name: "2",
      resource: {
        wood: 30,
        clay: 24,
        reed: 14,
        stone: 16,
        grain: 24,
        vegetable: 16,
        sheep: 18,
        boar: 15,
        cattle: 13,
        food: 76,
        family: 2,
        room: 2,
        fence: 0,
        barn: 0,
      },
      fields: [
        {
          field_type: "cage",
          position: 1,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 2,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 3,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 4,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 5,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 6,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 7,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 8,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 9,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 10,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 11,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 12,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 13,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "room",
          position: 14,
          is_in: {
            family: 1,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "room",
          position: 15,
          is_in: {
            family: 1,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
      ],
      house_type: "wood",
      fences: null,
      cards: [
        {
          card_number: "JOB_03",
          name: "\ubcbd \uac74\ucd95\uac00",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_03",
          name: "\ubcbd \uac74\ucd95\uac00",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_03",
          name: "\ubcbd \uac74\ucd95\uac00",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_03",
          name: "\ubcbd \uac74\ucd95\uac00",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_03",
          name: "\ubcbd \uac74\ucd95\uac00",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_03",
          name: "\ubcbd \uac74\ucd95\uac00",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_03",
          name: "\ubcbd \uac74\ucd95\uac00",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_12",
          name: "\ud0c0\uc791\ud310",
          score: 1,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_02",
          name: "\ub300\ud615\uc628\uc2e4",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_06",
          name: "\uc190\uc7c1\uae30",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_19",
          name: "\ubaa9\uc7ac\uc18c",
          score: 2,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_33",
          name: "\uc6b0\uc2dc\uc7a5",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_26",
          name: "\uc774\uc911\ub0a0 \uc7c1\uae30",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_10",
          name: "\uccad\uc5b4 \ub0c4\ube44",
          score: 0,
          is_used: false,
          used_round: null,
        },
      ],
    },
    {
      name: "3",
      resource: {
        wood: 30,
        clay: 24,
        reed: 14,
        stone: 16,
        grain: 24,
        vegetable: 16,
        sheep: 18,
        boar: 15,
        cattle: 13,
        food: 76,
        family: 2,
        room: 2,
        fence: 0,
        barn: 0,
      },
      fields: [
        {
          field_type: "cage",
          position: 1,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 2,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 3,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 4,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 5,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 6,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 7,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 8,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 9,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 10,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 11,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 12,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 13,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "room",
          position: 14,
          is_in: {
            family: 1,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "room",
          position: 15,
          is_in: {
            family: 1,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
      ],
      house_type: "wood",
      fences: null,
      cards: [
        {
          card_number: "JOB_03",
          name: "\ubcbd \uac74\ucd95\uac00",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_03",
          name: "\ubcbd \uac74\ucd95\uac00",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_03",
          name: "\ubcbd \uac74\ucd95\uac00",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_03",
          name: "\ubcbd \uac74\ucd95\uac00",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_03",
          name: "\ubcbd \uac74\ucd95\uac00",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_03",
          name: "\ubcbd \uac74\ucd95\uac00",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_03",
          name: "\ubcbd \uac74\ucd95\uac00",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_03",
          name: "\uc5f0\ubabb \uc624\ub450\ub9c9",
          score: 1,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_35",
          name: "\ubcd1",
          score: 4,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_31",
          name: "\ub178\uc810",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_34",
          name: "\uc774\ub3d9 \uacbd\uc791",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_23",
          name: "\ube75\uc0bd",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_22",
          name: "\ud3d0\ud488 \ucc3d\uace0",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_05",
          name: "\ub538\uae30\ud3ec",
          score: 2,
          is_used: false,
          used_round: null,
        },
      ],
    },
    {
      name: "4",
      resource: {
        wood: 30,
        clay: 24,
        reed: 14,
        stone: 16,
        grain: 24,
        vegetable: 16,
        sheep: 18,
        boar: 15,
        cattle: 13,
        food: 76,
        family: 2,
        room: 2,
        fence: 0,
        barn: 0,
      },
      fields: [
        {
          field_type: "cage",
          position: 1,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 2,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 3,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 4,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 5,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 6,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 7,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 8,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 9,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 10,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 11,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 12,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "cage",
          position: 13,
          is_in: {
            family: 0,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "room",
          position: 14,
          is_in: {
            family: 1,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
        {
          field_type: "room",
          position: 15,
          is_in: {
            family: 1,
            sheep: 0,
            boar: 0,
            cattle: 0,
            grain: 0,
            vegetable: 0,
          },
          is_barn: false,
        },
      ],
      house_type: "wood",
      fences: null,
      cards: [
        {
          card_number: "JOB_03",
          name: "\ubcbd \uac74\ucd95\uac00",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_03",
          name: "\ubcbd \uac74\ucd95\uac00",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_03",
          name: "\ubcbd \uac74\ucd95\uac00",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_03",
          name: "\ubcbd \uac74\ucd95\uac00",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_03",
          name: "\ubcbd \uac74\ucd95\uac00",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_03",
          name: "\ubcbd \uac74\ucd95\uac00",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "JOB_03",
          name: "\ubcbd \uac74\ucd95\uac00",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_04",
          name: "\uc190\uc218\ub808",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_15",
          name: "\ucc44\uad74 \ub9dd\uce58",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_01",
          name: "\ubd80\uc5cc\ubc29",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_24",
          name: "\ub124\ub35c\ub780\ub4dc\uc2dd \ud48d\ucc28",
          score: 2,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_18",
          name: "\uc591\ud1a0 \ucc44\uad74\uc7a5",
          score: 1,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_25",
          name: "\ub3cc \uc9d1\uac8c",
          score: 0,
          is_used: false,
          used_round: null,
        },
        {
          card_number: "SUB_FAC_16",
          name: "\ubc14\uad6c\ub2c8",
          score: 0,
          is_used: false,
          used_round: null,
        },
      ],
    },
  ],
  actions: [],
  base_cards: [
    {
      card_number: "BASE_01",
      is_stacked: true,
      count: 1,
      resource: { wood: 1 },
      additional_action: {
        "0": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "1": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "2": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "3": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "BASE_02",
      is_stacked: true,
      count: 2,
      resource: { wood: 2 },
      additional_action: {
        "0": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "1": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "2": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "3": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "BASE_03",
      is_stacked: false,
      count: 0,
      resource: { reed: 1, food: 1, stone: 1 },
      additional_action: {
        "0": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "1": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "2": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "3": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "BASE_04",
      is_stacked: true,
      count: 2,
      resource: { clay: 2 },
      additional_action: {
        "0": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "1": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "2": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "3": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "BASE_05",
      is_stacked: false,
      count: 0,
      resource: null,
      additional_action: {
        "0": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "1": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "2": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "3": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "BASE_06",
      is_stacked: true,
      count: 1,
      resource: { food: 1 },
      additional_action: {
        "0": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "1": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "2": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "3": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "BASE_07",
      is_stacked: false,
      count: 0,
      resource: null,
      additional_action: {
        "0": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "1": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "2": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "3": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "BASE_08",
      is_stacked: false,
      count: 0,
      resource: null,
      additional_action: {
        "0": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "1": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "2": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "3": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "BASE_09",
      is_stacked: false,
      count: 0,
      resource: { grain: 1 },
      additional_action: {
        "0": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "1": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "2": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "3": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "BASE_10",
      is_stacked: false,
      count: 0,
      resource: null,
      additional_action: {
        "0": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "1": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "2": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "3": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "BASE_11",
      is_stacked: false,
      count: 0,
      resource: null,
      additional_action: {
        "0": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "1": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "2": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "3": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "BASE_12",
      is_stacked: false,
      count: 0,
      resource: { food: 2 },
      additional_action: {
        "0": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "1": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "2": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "3": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "BASE_13",
      is_stacked: true,
      count: 3,
      resource: { wood: 3 },
      additional_action: {
        "0": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "1": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "2": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "3": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "BASE_14",
      is_stacked: true,
      count: 1,
      resource: { clay: 1 },
      additional_action: {
        "0": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "1": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "2": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "3": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "BASE_15",
      is_stacked: true,
      count: 1,
      resource: { reed: 1 },
      additional_action: {
        "0": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "1": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "2": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "3": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "BASE_16",
      is_stacked: true,
      count: 1,
      resource: { food: 1 },
      additional_action: {
        "0": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "1": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "2": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "3": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
  ],
  round_cards: [
    {
      card_number: "ACTION_03",
      is_stacked: false,
      count: 0,
      resource: null,
      additional_action: {
        "0": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "1": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "2": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "3": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "ACTION_01",
      is_stacked: false,
      count: 0,
      resource: null,
      additional_action: {
        "0": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "1": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "2": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "3": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "ACTION_04",
      is_stacked: true,
      count: 1,
      resource: { sheep: 1 },
      additional_action: {
        "0": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "1": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "2": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "3": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "ACTION_02",
      is_stacked: false,
      count: 0,
      resource: null,
      additional_action: {
        "0": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "1": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "2": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "3": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "ACTION_05",
      is_stacked: true,
      count: 1,
      resource: { stone: 1 },
      additional_action: {
        "0": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "1": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "2": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "3": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "ACTION_07",
      is_stacked: false,
      count: 0,
      resource: null,
      additional_action: {
        "0": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "1": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "2": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "3": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "ACTION_06",
      is_stacked: false,
      count: 0,
      resource: null,
      additional_action: {
        "0": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "1": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "2": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "3": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "ACTION_09",
      is_stacked: false,
      count: 0,
      resource: { vegetable: 1 },
      additional_action: {
        "0": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "1": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "2": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "3": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "ACTION_08",
      is_stacked: true,
      count: 1,
      resource: { boar: 1 },
      additional_action: {
        "0": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "1": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "2": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "3": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "ACTION_10",
      is_stacked: true,
      count: 1,
      resource: { stone: 1 },
      additional_action: {
        "0": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "1": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "2": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "3": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "ACTION_11",
      is_stacked: true,
      count: 1,
      resource: { cattle: 1 },
      additional_action: {
        "0": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "1": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "2": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "3": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "ACTION_13",
      is_stacked: false,
      count: 0,
      resource: null,
      additional_action: {
        "0": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "1": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "2": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "3": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "ACTION_12",
      is_stacked: false,
      count: 0,
      resource: null,
      additional_action: {
        "0": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "1": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "2": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "3": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
    {
      card_number: "ACTION_14",
      is_stacked: false,
      count: 0,
      resource: null,
      additional_action: {
        "0": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "1": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "2": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
        "3": {
          wood: 0,
          clay: 0,
          reed: 0,
          stone: 0,
          grain: 0,
          vegetable: 0,
          sheep: 0,
          boar: 0,
          cattle: 0,
          food: 0,
        },
      },
      player: null,
    },
  ],
  primary_cards: [
    { card_number: "PRI_FAC_01", owner: null },
    { card_number: "PRI_FAC_02", owner: null },
    { card_number: "PRI_FAC_03", owner: null },
    { card_number: "PRI_FAC_04", owner: null },
    { card_number: "PRI_FAC_05", owner: null },
    { card_number: "PRI_FAC_06", owner: null },
    { card_number: "PRI_FAC_07", owner: null },
    { card_number: "PRI_FAC_08", owner: null },
  ],
  common_resources: {
    wood: 24,
    clay: 21,
    reed: 13,
    stone: 14,
    grain: 24,
    vegetable: 16,
    sheep: 17,
    boar: 14,
    cattle: 12,
    food: 74,
    family: 0,
    room: 0,
    fence: 0,
    barn: 0,
  },
};

export const createRoom = {
  room_id: 0,
  host: "User",
  option: {
    title: " ",
    is_chat: null,
    mode: null,
    time: null,
    password: null,
  },
  participant: [],
};

export const RoomData1 = {
  room_id: 1,
  host: "Player 1",
  option: {
    title: "Room 1",
    is_chat: false,
    mode: "public",
    time: 30,
    password: "1234",
  },
  participant: [
    {
      name: "Player 1",
      img: "https://i.imgur.com/1Q2QXem.png",
      user_detail: "rest_endPoint2",
    },
    {
      name: "Player 2",
      img: "https://i.imgur.com/1Q2QXem.png",
      user_detail: "rest_endPoint2",
    },
    {
      name: "Player 3",
      img: "https://i.imgur.com/1Q2QXem.png",
      user_detail: "rest_endPoint3",
    },
    {
      name: "Player 4",
      img: "https://i.imgur.com/1Q2QXem.png",
      user_detail: "rest_endPoint4",
    },
  ],
};

export const RoomData2 = {
  room_id: 2,
  host: "윤호",
  option: {
    title: "일해라 노예야",
    is_chat: true,
    mode: "private",
    time: 30,
    password: "1234",
  },
  participant: [
    {
      name: "재훈",
      img: "https://i.imgur.com/1Q2QXem.png",
      user_detail: "rest_endPoint2",
    },
    {
      name: "준수",
      img: "https://i.imgur.com/1Q2QXem.png",
      user_detail: "rest_endPoint2",
    },
    {
      name: "윤호",
      img: "https://i.imgur.com/1Q2QXem.png",
      user_detail: "rest_endPoint3",
    },
  ],
};

// TODO : socket 통신 시에는 각 방의 정보만 받아옴
export const detailRoomData = {
  data: [createRoom, RoomData1, RoomData2],
};

export const lobbyData = {
  room_list: [
    {
      room_id: 1,
      host: "Player 1",
      option: {
        title: "Room 1",
        is_chat: true,
        mode: "public",
        time: 30,
        password: null,
      },
      participant: [
        {
          name: "Player 1",
          img: "https://i.imgur.com/1Q2QXem.png",
          user_detail: "rest_endPoint2",
        },
        {
          name: "Player 2",
          img: "https://i.imgur.com/1Q2QXem.png",
          user_detail: "rest_endPoint2",
        },
        {
          name: "Player 3",
          img: "https://i.imgur.com/1Q2QXem.png",
          user_detail: "rest_endPoint3",
        },
        {
          name: "Player 4",
          img: "https://i.imgur.com/1Q2QXem.png",
          user_detail: "rest_endPoint4",
        },
      ],
    },
    {
      room_id: 2,
      host: "재훈",
      option: {
        title: "일해라 노예야",
        is_chat: true,
        mode: "private",
        time: 30,
        password: "1234",
      },
      participant: [
        {
          name: "재훈",
          img: "https://i.imgur.com/1Q2QXem.png",
          user_detail: "rest_endPoint2",
        },
        {
          name: "Player 2",
          img: "https://i.imgur.com/1Q2QXem.png",
          user_detail: "rest_endPoint2",
        },
        {
          name: "Player 3",
          img: "https://i.imgur.com/1Q2QXem.png",
          user_detail: "rest_endPoint3",
        },
      ],
    },
  ],
};
